const data = {
    images: [
        {
            id: 1,
            dataName: 'aquaman',
            src: './assets/aquaman.jpg',
            title: 'Aquaman',
        },
        {
            id: 2,
            dataName: 'avatar',
            src: './assets/avatar.png',
            title: 'Avatar',
        },
        {
            id: 3,
            dataName: 'avatar-the-way-of-water',
            src: './assets/avatar-the-way-of-water.jpeg',
            title: 'Avatar: The way of water',
        },
        {
            id: 4,
            dataName: 'avengers',
            src: './assets/avengers.jpg',
            title: 'Avengers',
        },
        {
            id: 5,
            dataName: 'avengers-age-of-ultron',
            src: './assets/avengers-age-of-ultron.jpg',
            title: 'Avengers: Age of ultron',
        },
        {
            id: 6,
            dataName: 'avengers-end-game',
            src: './assets/avengers-end-game.jpg',
            title: 'Avengers: End game',
        },
        {
            id: 7,
            dataName: 'avengers-infinity-war',
            src: './assets/avengers-infinity-war.jpg',
            title: 'Avenger: Infinity war',
        },
        {
            id: 8,
            dataName: 'barbie',
            src: './assets/barbie.jpg',
            title: 'Barbie',
        },
        {
            id: 9,
            dataName: 'beauty-beast',
            src: './assets/beauty-beast.png',
            title: 'Beauty and the beast',
        },
        {
            id: 10,
            dataName: 'black-panther',
            src: './assets/black-panther.jpg',
            title: 'Black panther',
        },
        {
            id: 11,
            dataName: 'captain-america-civil-war',
            src: './assets/captain-america-civil-war.jpg',
            title: 'Captain America: Civil war',
        },
        {
            id: 12,
            dataName: 'captain-marvel',
            src: './assets/captain-marvel.jpeg',
            title: 'Captain marvel',
        },
        {
            id: 13,
            dataName: 'frozen',
            src: './assets/frozen.jpeg',
            title: 'Frozen',
        },
        {
            id: 14,
            dataName: 'frozen-2',
            src: './assets/frozen-2.jpeg',
            title: 'Frozen 2',
        },
        {
            id: 15,
            dataName: 'furious-7',
            src: './assets/furious-7.jpg',
            title: 'Furious 7',
        },
        {
            id: 16,
            dataName: 'incredibles-2',
            src: './assets/incredibles-2.jpg',
            title: 'Incredibles 2',
        },
        {
            id: 17,
            dataName: 'iron-man-3',
            src: './assets/iron-man-3.jpg',
            title: 'Iron man 3',
        },
        {
            id: 18,
            dataName: 'jurassic-world',
            src: './assets/jurassic-world.jpg',
            title: 'Jurassic World ',
        },
        {
            id: 19,
            dataName: 'jurassic-world-fallen-kingdom',
            src: './assets/jurassic-world-fallen-kingdom.jpg',
            title: 'Jurassic World: Fallen-kingdom ',
        },
        {
            id: 20,
            dataName: 'minions',
            src: './assets/minions.jpg',
            title: 'Minions',
        },
        {
            id: 21,
            dataName: 'spiderman',
            src: './assets/spiderman.jpg',
            title: 'Spiderman',
        },
        {
            id: 22,
            dataName: 'spiderman-far-from-home',
            src: './assets/spiderman-far-from-home.jpg',
            title: 'Spiderman: Far from home',
        },
        {
            id: 23,
            dataName: 'starwars-the-force-awakens.',
            src: './assets/starwars-the-force-awakens.png',
            title: 'Starwars: The force awakens.',
        },
        {
            id: 24,
            dataName: 'star-wars-the-last-jedi',
            src: './assets/star-wars-the-last-jedi.jpg',
            title: 'Star Wars: The last jedi',
        },
        {
            id: 25,
            dataName: 'the-fate-of-the-furious',
            src: './assets/the-fate-of-the-furious.jpg',
            title: 'The fate of the furious',
        },
        {
            id: 26,
            dataName: 'the-lion-king',
            src: './assets/the-lion-king.jpg',
            title: 'The lion king',
        },
        {
            id: 27,
            dataName: 'the-lord-of-the-rings-the-return-of-the-king',
            src: './assets/the-lord-of-the-rings-the-return-of-the-king.png',
            title: 'The lord of the rings: The return of the king',
        },
        {
            id: 28,
            dataName: 'titanic',
            src: './assets/titanic.png',
            title: 'Titanic',
        },
        {
            id: 29,
            dataName: 'top-gun-maverick',
            src: './assets/top-gun-maverick.jpg',
            title: 'Top gun maverick',
        },
        {
            id: 30,
            dataName: 'transformers-dark-of-the-moon',
            src: './assets/transformers-dark-of-the-moon.jpg',
            title: 'Transformers: Dark of the moon',
        },
    ],
    posters: [],
};

export default data;
